/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas.siprus.ui;

import java.sql.SQLException;
import java.util.List;
import uas.siprus.Anggota;
import uas.siprus.model.AnggotaDataTable;
import uas.siprus.model.AnggotaModel;

/**
 *
 * @author null
 */
public class AnggotaFrame extends javax.swing.JInternalFrame {

    static AnggotaFrame instance = null;
    List<Anggota> dataAnggota;
    
    public static AnggotaFrame getInstance(){
        if (instance == null) {
            instance = new AnggotaFrame();
        }
        return instance;
    }
    /**
     * Creates new form Anggota
     */
    public AnggotaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchForm = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        anggotaScroll = new javax.swing.JScrollPane();
        anggotaTable = new javax.swing.JTable();
        detailButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        tutupButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(650, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("List Anggota");

        searchForm.setText("search");
        searchForm.setToolTipText("");

        cariButton.setText("Cari");

        resetButton.setText("Reset");

        anggotaScroll.setPreferredSize(new java.awt.Dimension(450, 400));

        anggotaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Anggota", "Nama", "Pekerjaan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        anggotaScroll.setViewportView(anggotaTable);
        if (anggotaTable.getColumnModel().getColumnCount() > 0) {
            anggotaTable.getColumnModel().getColumn(0).setMinWidth(100);
            anggotaTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        detailButton.setText("Lihat Detail");
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        tambahButton.setText("Tambah Anggota");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        tutupButton.setText("Tutup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchForm, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(anggotaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(detailButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambahButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tutupButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton)
                    .addComponent(cariButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anggotaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailButton)
                    .addComponent(tambahButton)
                    .addComponent(tutupButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        // TODO add your handling code here:
        AnggotaDetail anggotaDetail = AnggotaDetail.getInstance();
        anggotaDetail.tampilDetailAnggota(anggotaTable.getValueAt(anggotaTable.getSelectedRow(),0).toString());
    }//GEN-LAST:event_detailButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        AnggotaDetail anggotaDetail = AnggotaDetail.getInstance();
        anggotaDetail.aktifkanModeForm(AnggotaDetail.MODE_TAMBAH);
    }//GEN-LAST:event_tambahButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane anggotaScroll;
    private javax.swing.JTable anggotaTable;
    private javax.swing.JButton cariButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField searchForm;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables
    public void tampilkanListAnggota(String param){
        try{
            dataAnggota = AnggotaModel.getInstance().getListAnggota(param);          
        }catch (SQLException ex){
            ex.printStackTrace();
        }
        
        anggotaTable.setModel(new AnggotaDataTable(dataAnggota));
        if (anggotaTable.getModel().getRowCount()>0) {
            anggotaTable.setRowSelectionInterval(0,0);
        }
    }
    
}
